run:
	mix test && mix run -e 'Marble.part1(["input/input.txt"])' && mix run -e 'Marble.part2(["input/input.txt"])'

examples:
	mix test && mix run -e 'Marble.part1(["input/example1.txt"])' && mix run -e 'Marble.part2(["input/example1.txt"])' \
		&& mix run -e 'Marble.part1(["input/example2.txt"])' && mix run -e 'Marble.part2(["input/example2.txt"])' \
		&& mix run -e 'Marble.part1(["input/example3.txt"])' && mix run -e 'Marble.part2(["input/example3.txt"])' \
		&& mix run -e 'Marble.part1(["input/example4.txt"])' && mix run -e 'Marble.part2(["input/example4.txt"])' \
		&& mix run -e 'Marble.part1(["input/example5.txt"])' && mix run -e 'Marble.part2(["input/example5.txt"])' \
		&& mix run -e 'Marble.part1(["input/example6.txt"])' && mix run -e 'Marble.part2(["input/example6.txt"])'
