[package]
name = "euler-rust"
version = "0.1.0"
authors = ["bjn"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_error = "1.8.0"
maplit = "1"
rug = "1.11.0"
