all:
	mix test && mix run -e 'Chronal.part1(["input/input.txt"])' && mix run -e 'Chronal.part2(["input/input.txt"])'

example:
	mix test && mix run -e 'Chronal.part1(["input/example1.txt"])' && mix run -e 'Chronal.part2(["input/example1.txt"])'
