run:
	mix run -e 'Depth.part1(["input/input.txt"])'  #&& mix run -e 'Depth.part2(["input/input.txt"])'

example:
	mix run -e 'Depth.part1(["input/example1.txt"])'  #&& mix run -e 'Depth.part2(["input/example1.txt"])'
