[package]
name = "interact_io"
version = "0.2.0"
authors = ["Brent J. Nordquist <brent@nordist.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
