run:
	mix test && mix run -e 'Plants.part1(["input/input.txt"])' && mix run -e 'Plants.part2(["input/input.txt"])'

examples:
	mix test && mix run -e 'Plants.part1(["input/example1.txt"])' && mix run -e 'Plants.part2(["input/example1.txt"])' \
		&& mix run -e 'Plants.part1(["input/example2.txt"])' && mix run -e 'Plants.part2(["input/example2.txt"])' \
		&& mix run -e 'Plants.part1(["input/example3.txt"])' && mix run -e 'Plants.part2(["input/example3.txt"])' \
		&& mix run -e 'Plants.part1(["input/example4.txt"])' && mix run -e 'Plants.part2(["input/example4.txt"])'
