run:
	mix test && mix run -e 'Plants.part1(["input/input.txt"])' && mix run -e 'Plants.part2(["input/input.txt"])'

example:
	mix test && mix run -e 'Plants.part1(["input/example1.txt"])' && mix run -e 'Plants.part2(["input/example1.txt"])'
