run:
	mix test && mix run -e 'FuelCell.part1(["input/input.txt"])' && mix run -e 'FuelCell.part2(["input/input.txt"])'

examples:
	mix test && mix run -e 'FuelCell.part1(["input/example1.txt"])' && mix run -e 'FuelCell.part2(["input/example1.txt"])' \
		&& mix run -e 'FuelCell.part1(["input/example2.txt"])' && mix run -e 'FuelCell.part2(["input/example2.txt"])'
