defmodule SplitTest do
  use ExUnit.Case
  doctest Split

  describe "puzzle example" do
    setup do
      [
        inputs: [
          """
          ...S...
          .......
          ...^...
          .......
          ..^.^..
          .......
          """,
          """
          .......S.......
          ...............
          .......^.......
          ...............
          ......^.^......
          ...............
          .....^.^.^.....
          ...............
          ....^.^...^....
          ...............
          ...^.^...^.^...
          ...............
          ..^...^.....^..
          ...............
          .^.^.^.^.^...^.
          ...............
          """,
        ],
        exp_split_counts: [
          3,
          21,
        ],
        exp_world_counts: [
          4,
          40,
        ],
      ]
    end

    test "produces correct split counts", fixture do
      act_split_counts =
        fixture.inputs
        |> Enum.map(&Split.Parser.parse_input_string/1)
        |> Enum.map(&Split.count_splits/1)
      assert act_split_counts == fixture.exp_split_counts
    end

    test "produces correct world counts", fixture do
      act_world_counts =
        fixture.inputs
        |> Enum.map(&Split.Parser.parse_input_string/1)
        |> Enum.map(&Split.count_worlds/1)
      assert act_world_counts == fixture.exp_world_counts
    end
  end
end
