graph TD
A[Ladder]-->|north|B
B[Northloop]-->|south|A
B-->|west|B
B-->|north|C
C[Southloop]-->|south|B
C-->|north|A
C-->|east|C
A-->|south|C
A-->|west|D
D[Westside]-->|east|A
D-->|north|D
A-->|east|E
E[Gruesound]-->|west|A
E-->|south|E
E-->|east|N
N[Gruetoo?]
E-->|north|K
D-->|south|G
G[Gruelikely]-->|north=code|H
H[Canroom]-->|west|A
G-->|south|B
G-->|west|C
G-->|east|F
F[Grue?]
K[Nintendo]-->|north|L
K-->|south|K
K-->|east|M
L[Lenny]-->|north|A
M[Aussie]-->|west|M
M-->|north|L
M-->|south|A
L-->|south|M
L-->|east|L
