[package]
name = "day-04"
version = "0.1.0"
authors = ["Brent J. Nordquist <brent@nordist.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"
